name: "build-classic2"

on:
  schedule:
    - cron: '30 19 * * 0,1,2,3,4'
  workflow_dispatch:

jobs:
  build-classic2:
    runs-on: ubuntu-20.04

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: Populate vars
        id: vars
        run: |
          BOOT_VERSION=$(./tools/version.sh ./legacy/bootloader/version.h)
          FIRMWARE_VERSION=$(cat ./legacy/firmware/version.h | grep "ONEKEY_VERSION " | awk -F "[\"\"]" '{print $2}')
          BUILD_DATE=$(date +"%Y%m%d")
          SHORT_HASH=$(git rev-parse --short HEAD)

          echo "BOOT_VERSION=$BOOT_VERSION" >> $GITHUB_ENV
          echo "BUILD_DATE=$BUILD_DATE" >> $GITHUB_ENV
          echo "SHORT_HASH=$SHORT_HASH" >> $GITHUB_ENV
          echo "FIRMWARE_VERSION=$FIRMWARE_VERSION" >> $GITHUB_ENV
          echo "ARTIFACTS_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"" >> $GITHUB_ENV

      - name: "Build classic2 firmware"
        run: |
          sh <(curl -L https://nixos.org/nix/install) --no-daemon
          . $HOME/.nix-profile/etc/profile.d/nix.sh
          nix-shell --run "poetry install"
          nix-shell --run "poetry run ./legacy/script/setup"
          nix-shell --run "poetry run ./legacy/script/cibuild"

      - name: "Upload Artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: firmware-classic2-${{ github.sha }}
          path: |
            ./legacy/firmware/classic*Stable*.bin
            ./legacy/bootloader/bootloader*Stable*.bin
            ./legacy/intermediate_fw/classic*.bin

      - name: "Notify to Slack"
        uses: onekeyhq/actions/notice-slack-app-update@main
        with:
          web-hook-url: ${{ secrets.SLACK_DEV_RELEASE_WEBHOOK }}
          artifact-type: CLASSIC-FIRMWARE-2
          artifact-name: Classic-Hardware-Firmware-2
          artifact-bundle-id: 'so.onekey.firmware.classic2'
          artifact-version-name: '${{ env.FIRMWARE_VERSION }}'
          artifact-version-code: '${{ env.SHORT_HASH }}-${{ env.BUILD_DATE }}'
          artifact-download-url: '${{ env.ARTIFACTS_URL }}'
          change-log: 'firmware@${{ env.FIRMWARE_VERSION }} / boot@${{ env.BOOT_VERSION }}'
          custom-issue-url: ''
          custom-message-title: ''
          custom-message-payload: ''